project:
  type: website

website:
  title: Data Analysis Learning Portfolio
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: learning-plan.qmd
        text: Learning Plan
      - href: r/r_audit.qmd
        text: R Audit
      - href: notebooks/python_audit.ipynb
        text: Python Audit
      
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



